version: "3.3"

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Cyber123&"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlvolume:/var/opt/mssql

  microservice-account:
    build: 
      context: ./accounts
    env_file: ./.env
    command: node accounts
    volumes:
      - .:/accounts
      - /accounts/node_modules
    ports:
      - "3000:3000"
    container_name: accounts
    depends_on: 
      - reverse-proxy
      - sql-server-db  
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MSSQLDB_DOCKER_PORT   
    stdin_open: true
    tty: true

  reverse-proxy:
    container_name: reverse-proxy
    hostname: reverse-proxy
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  whoami:
    image: containous/whoami
    container_name: whoami


# Names our volume
volumes:
  sqlvolume:
    driver: local
  reverse-proxy: